source_a:
  type: file
  path: "files/input/origemA.txt"
  sep: ";"
  quotechar: "\""
  encoding: "utf-8"

source_b:
  type: database
  conn_str: "postgresql://postgres:Oshikawa!8@localhost:5432/comparador"
  table: "origemB"

comparison:
  key: "MES_REFERENCIA,NIS_FAVORECIDO"
  ignore_columns: ["VALOR PARCELA"]

report:
  output_file: "files/outpyt/relatorio_diff.csv"
  save_to_db: true
  db_url: "postgresql://postgres:Oshikawa!8@localhost:5432/comparador"
  db_table: "relatorio_diferencas"
